/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/admin/AdminLayout.vue')['default']
    DetectionCard: typeof import('./src/components/user/DetectionCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmojiManagementPanel: typeof import('./src/components/user/EmojiManagementPanel.vue')['default']
    EmojiPicker: typeof import('./src/components/user/EmojiPicker.vue')['default']
    EmojiSuggestionCard: typeof import('./src/components/user/EmojiSuggestionCard.vue')['default']
    HighlightEditor: typeof import('./src/components/user/HighlightEditor.vue')['default']
    ReplacementPanel: typeof import('./src/components/user/ReplacementPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/admin/StatCard.vue')['default']
    TopNavBar: typeof import('./src/components/common/TopNavBar.vue')['default']
    UsageChart: typeof import('./src/components/admin/UsageChart.vue')['default']
    WordTooltip: typeof import('./src/components/user/WordTooltip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
